version: '3'
services:
  spark-master:
    image: e-check-project-image:1.0
    container_name: spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master", "--host", "spark-master"]
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - /home/arthur/projects/e-check-project/source_data:/opt/spark/source_data
      - /home/arthur/projects/e-check-project/code_exe:/opt/spark/code_exe
      - /home/arthur/projects/e-check-project/sink_data:/opt/spark/sink_data
      - /home/arthur/projects/e-check-project/google_auth:/opt/spark/google_auth:ro
      - /home/arthur/projects/e-check-project/spark-conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - /home/arthur/projects/e-check-project/logs:/opt/spark/logs
      - /home/arthur/projects/e-check-project/.env:/opt/spark/.env:ro
    
  spark-worker:
    image: e-check-project-image:1.0
    container_name: spark-worker
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - /home/arthur/projects/e-check-project/source_data:/opt/spark/source_data
      - /home/arthur/projects/e-check-project/code_exe:/opt/spark/code_exe
      - /home/arthur/projects/e-check-project/sink_data:/opt/spark/sink_data
      - /home/arthur/projects/e-check-project/google_auth:/opt/spark/google_auth:ro
      - /home/arthur/projects/e-check-project/spark-conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - /home/arthur/projects/e-check-project/logs:/opt/spark/logs
      - /home/arthur/projects/e-check-project/.env:/opt/spark/.env:ro
    depends_on:
      - spark-master
      
